/* tslint:disable */
/* eslint-disable */
/**
 * HabitMuse API
 * API для управления привычками и пользователями
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BodyMetricsBodyMetricDTO,
  DtoErrorResponse,
} from '../models/index';
import {
    BodyMetricsBodyMetricDTOFromJSON,
    BodyMetricsBodyMetricDTOToJSON,
    DtoErrorResponseFromJSON,
    DtoErrorResponseToJSON,
} from '../models/index';

/**
 * BodyMetricApi - interface
 * 
 * @export
 * @interface BodyMetricApiInterface
 */
export interface BodyMetricApiInterface {
    /**
     * Возвращает список всех записей метрик тела текущего авторизованного пользователя
     * @summary Получить список всех метрик тела пользователя
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BodyMetricApiInterface
     */
    bodyMetricAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BodyMetricsBodyMetricDTO>>>;

    /**
     * Возвращает список всех записей метрик тела текущего авторизованного пользователя
     * Получить список всех метрик тела пользователя
     */
    bodyMetricAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BodyMetricsBodyMetricDTO>>;

}

/**
 * 
 */
export class BodyMetricApi extends runtime.BaseAPI implements BodyMetricApiInterface {

    /**
     * Возвращает список всех записей метрик тела текущего авторизованного пользователя
     * Получить список всех метрик тела пользователя
     */
    async bodyMetricAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BodyMetricsBodyMetricDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/body-metric/all`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BodyMetricsBodyMetricDTOFromJSON));
    }

    /**
     * Возвращает список всех записей метрик тела текущего авторизованного пользователя
     * Получить список всех метрик тела пользователя
     */
    async bodyMetricAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BodyMetricsBodyMetricDTO>> {
        const response = await this.bodyMetricAllGetRaw(initOverrides);
        return await response.value();
    }

}
