/* tslint:disable */
/* eslint-disable */
/**
 * HabitMuse API
 * API для управления привычками и пользователями
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BodyMetricsBodyMetricDTO,
  DtoErrorResponse,
} from '../models/index';
import {
    BodyMetricsBodyMetricDTOFromJSON,
    BodyMetricsBodyMetricDTOToJSON,
    DtoErrorResponseFromJSON,
    DtoErrorResponseToJSON,
} from '../models/index';

export interface ApiBodyMetricCreatePostRequest {
    metric: BodyMetricsBodyMetricDTO;
}

/**
 * BodyMetricsApi - interface
 * 
 * @export
 * @interface BodyMetricsApiInterface
 */
export interface BodyMetricsApiInterface {
    /**
     * 
     * @summary Создать метрику тела
     * @param {BodyMetricsBodyMetricDTO} metric Данные метрики
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BodyMetricsApiInterface
     */
    apiBodyMetricCreatePostRaw(requestParameters: ApiBodyMetricCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BodyMetricsBodyMetricDTO>>;

    /**
     * Создать метрику тела
     */
    apiBodyMetricCreatePost(requestParameters: ApiBodyMetricCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BodyMetricsBodyMetricDTO>;

    /**
     * 
     * @summary Получить отчет по метрикам тела
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BodyMetricsApiInterface
     */
    apiBodyMetricGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Получить отчет по метрикам тела
     */
    apiBodyMetricGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

}

/**
 * 
 */
export class BodyMetricsApi extends runtime.BaseAPI implements BodyMetricsApiInterface {

    /**
     * Создать метрику тела
     */
    async apiBodyMetricCreatePostRaw(requestParameters: ApiBodyMetricCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BodyMetricsBodyMetricDTO>> {
        if (requestParameters['metric'] == null) {
            throw new runtime.RequiredError(
                'metric',
                'Required parameter "metric" was null or undefined when calling apiBodyMetricCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/body-metric/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyMetricsBodyMetricDTOToJSON(requestParameters['metric']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BodyMetricsBodyMetricDTOFromJSON(jsonValue));
    }

    /**
     * Создать метрику тела
     */
    async apiBodyMetricCreatePost(requestParameters: ApiBodyMetricCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BodyMetricsBodyMetricDTO> {
        const response = await this.apiBodyMetricCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Получить отчет по метрикам тела
     */
    async apiBodyMetricGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/body-metric`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Получить отчет по метрикам тела
     */
    async apiBodyMetricGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiBodyMetricGetRaw(initOverrides);
        return await response.value();
    }

}
