/* tslint:disable */
/* eslint-disable */
/**
 * HabitMuse API
 * API для управления привычками и пользователями
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyMetricsBodyMetricDTO
 */
export interface BodyMetricsBodyMetricDTO {
    /**
     * 
     * @type {number}
     * @memberof BodyMetricsBodyMetricDTO
     */
    belly?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyMetricsBodyMetricDTO
     */
    bicepsLeft?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyMetricsBodyMetricDTO
     */
    bicepsRight?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyMetricsBodyMetricDTO
     */
    chest?: number;
    /**
     * 
     * @type {string}
     * @memberof BodyMetricsBodyMetricDTO
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof BodyMetricsBodyMetricDTO
     */
    hips?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyMetricsBodyMetricDTO
     */
    thighLowLeft?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyMetricsBodyMetricDTO
     */
    thighLowRight?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyMetricsBodyMetricDTO
     */
    thighMaxLeft?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyMetricsBodyMetricDTO
     */
    thighMaxRight?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyMetricsBodyMetricDTO
     */
    waist?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyMetricsBodyMetricDTO
     */
    weight?: number;
}

/**
 * Check if a given object implements the BodyMetricsBodyMetricDTO interface.
 */
export function instanceOfBodyMetricsBodyMetricDTO(value: object): value is BodyMetricsBodyMetricDTO {
    if (!('date' in value) || value['date'] === undefined) return false;
    return true;
}

export function BodyMetricsBodyMetricDTOFromJSON(json: any): BodyMetricsBodyMetricDTO {
    return BodyMetricsBodyMetricDTOFromJSONTyped(json, false);
}

export function BodyMetricsBodyMetricDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyMetricsBodyMetricDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'belly': json['belly'] == null ? undefined : json['belly'],
        'bicepsLeft': json['biceps_left'] == null ? undefined : json['biceps_left'],
        'bicepsRight': json['biceps_right'] == null ? undefined : json['biceps_right'],
        'chest': json['chest'] == null ? undefined : json['chest'],
        'date': json['date'],
        'hips': json['hips'] == null ? undefined : json['hips'],
        'thighLowLeft': json['thigh_low_left'] == null ? undefined : json['thigh_low_left'],
        'thighLowRight': json['thigh_low_right'] == null ? undefined : json['thigh_low_right'],
        'thighMaxLeft': json['thigh_max_left'] == null ? undefined : json['thigh_max_left'],
        'thighMaxRight': json['thigh_max_right'] == null ? undefined : json['thigh_max_right'],
        'waist': json['waist'] == null ? undefined : json['waist'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function BodyMetricsBodyMetricDTOToJSON(json: any): BodyMetricsBodyMetricDTO {
    return BodyMetricsBodyMetricDTOToJSONTyped(json, false);
}

export function BodyMetricsBodyMetricDTOToJSONTyped(value?: BodyMetricsBodyMetricDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'belly': value['belly'],
        'biceps_left': value['bicepsLeft'],
        'biceps_right': value['bicepsRight'],
        'chest': value['chest'],
        'date': value['date'],
        'hips': value['hips'],
        'thigh_low_left': value['thighLowLeft'],
        'thigh_low_right': value['thighLowRight'],
        'thigh_max_left': value['thighMaxLeft'],
        'thigh_max_right': value['thighMaxRight'],
        'waist': value['waist'],
        'weight': value['weight'],
    };
}

