/* tslint:disable */
/* eslint-disable */
/**
 * HabitMuse API
 * API для управления привычками и пользователями
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoErrorResponse
 */
export interface DtoErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoErrorResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the DtoErrorResponse interface.
 */
export function instanceOfDtoErrorResponse(value: object): value is DtoErrorResponse {
    return true;
}

export function DtoErrorResponseFromJSON(json: any): DtoErrorResponse {
    return DtoErrorResponseFromJSONTyped(json, false);
}

export function DtoErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function DtoErrorResponseToJSON(json: any): DtoErrorResponse {
    return DtoErrorResponseToJSONTyped(json, false);
}

export function DtoErrorResponseToJSONTyped(value?: DtoErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

