/* tslint:disable */
/* eslint-disable */
/**
 * HabitMuse API
 * API для управления привычками и пользователями
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoSuccessResponse
 */
export interface DtoSuccessResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoSuccessResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the DtoSuccessResponse interface.
 */
export function instanceOfDtoSuccessResponse(value: object): value is DtoSuccessResponse {
    return true;
}

export function DtoSuccessResponseFromJSON(json: any): DtoSuccessResponse {
    return DtoSuccessResponseFromJSONTyped(json, false);
}

export function DtoSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoSuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function DtoSuccessResponseToJSON(json: any): DtoSuccessResponse {
    return DtoSuccessResponseToJSONTyped(json, false);
}

export function DtoSuccessResponseToJSONTyped(value?: DtoSuccessResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

