/* tslint:disable */
/* eslint-disable */
/**
 * HabitMuse API
 * API для управления привычками и пользователями
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HabitsCreateHabitDto
 */
export interface HabitsCreateHabitDto {
    /**
     * 
     * @type {string}
     * @memberof HabitsCreateHabitDto
     */
    color: string;
    /**
     * 
     * @type {string}
     * @memberof HabitsCreateHabitDto
     */
    daysOfWeek?: string;
    /**
     * 
     * @type {string}
     * @memberof HabitsCreateHabitDto
     */
    desc?: string;
    /**
     * "2025-06-28T00:00:00Z"
     * @type {string}
     * @memberof HabitsCreateHabitDto
     */
    firstDate: string;
    /**
     * 
     * @type {string}
     * @memberof HabitsCreateHabitDto
     */
    icon: string;
    /**
     * 
     * @type {string}
     * @memberof HabitsCreateHabitDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof HabitsCreateHabitDto
     */
    repeatType: string;
}

/**
 * Check if a given object implements the HabitsCreateHabitDto interface.
 */
export function instanceOfHabitsCreateHabitDto(value: object): value is HabitsCreateHabitDto {
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('firstDate' in value) || value['firstDate'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('repeatType' in value) || value['repeatType'] === undefined) return false;
    return true;
}

export function HabitsCreateHabitDtoFromJSON(json: any): HabitsCreateHabitDto {
    return HabitsCreateHabitDtoFromJSONTyped(json, false);
}

export function HabitsCreateHabitDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HabitsCreateHabitDto {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'],
        'daysOfWeek': json['daysOfWeek'] == null ? undefined : json['daysOfWeek'],
        'desc': json['desc'] == null ? undefined : json['desc'],
        'firstDate': json['firstDate'],
        'icon': json['icon'],
        'name': json['name'],
        'repeatType': json['repeatType'],
    };
}

export function HabitsCreateHabitDtoToJSON(json: any): HabitsCreateHabitDto {
    return HabitsCreateHabitDtoToJSONTyped(json, false);
}

export function HabitsCreateHabitDtoToJSONTyped(value?: HabitsCreateHabitDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'daysOfWeek': value['daysOfWeek'],
        'desc': value['desc'],
        'firstDate': value['firstDate'],
        'icon': value['icon'],
        'name': value['name'],
        'repeatType': value['repeatType'],
    };
}

