/* tslint:disable */
/* eslint-disable */
/**
 * HabitMuse API
 * API для управления привычками и пользователями
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HabitsHabitDto
 */
export interface HabitsHabitDto {
    /**
     * 
     * @type {string}
     * @memberof HabitsHabitDto
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof HabitsHabitDto
     */
    daysOfWeek?: string;
    /**
     * 
     * @type {string}
     * @memberof HabitsHabitDto
     */
    desc?: string;
    /**
     * "2025-06-28T00:00:00Z"
     * @type {string}
     * @memberof HabitsHabitDto
     */
    firstDate?: string;
    /**
     * 
     * @type {string}
     * @memberof HabitsHabitDto
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof HabitsHabitDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof HabitsHabitDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof HabitsHabitDto
     */
    repeatType?: string;
    /**
     * 
     * @type {number}
     * @memberof HabitsHabitDto
     */
    versionId?: number;
}

/**
 * Check if a given object implements the HabitsHabitDto interface.
 */
export function instanceOfHabitsHabitDto(value: object): value is HabitsHabitDto {
    return true;
}

export function HabitsHabitDtoFromJSON(json: any): HabitsHabitDto {
    return HabitsHabitDtoFromJSONTyped(json, false);
}

export function HabitsHabitDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HabitsHabitDto {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'] == null ? undefined : json['color'],
        'daysOfWeek': json['daysOfWeek'] == null ? undefined : json['daysOfWeek'],
        'desc': json['desc'] == null ? undefined : json['desc'],
        'firstDate': json['firstDate'] == null ? undefined : json['firstDate'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'repeatType': json['repeatType'] == null ? undefined : json['repeatType'],
        'versionId': json['versionId'] == null ? undefined : json['versionId'],
    };
}

export function HabitsHabitDtoToJSON(json: any): HabitsHabitDto {
    return HabitsHabitDtoToJSONTyped(json, false);
}

export function HabitsHabitDtoToJSONTyped(value?: HabitsHabitDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'daysOfWeek': value['daysOfWeek'],
        'desc': value['desc'],
        'firstDate': value['firstDate'],
        'icon': value['icon'],
        'id': value['id'],
        'name': value['name'],
        'repeatType': value['repeatType'],
        'versionId': value['versionId'],
    };
}

