/* tslint:disable */
/* eslint-disable */
/**
 * HabitMuse API
 * API для управления привычками и пользователями
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HabitsCompletionRequest
 */
export interface HabitsCompletionRequest {
    /**
     * 
     * @type {boolean}
     * @memberof HabitsCompletionRequest
     */
    completed?: boolean;
}

/**
 * Check if a given object implements the HabitsCompletionRequest interface.
 */
export function instanceOfHabitsCompletionRequest(value: object): value is HabitsCompletionRequest {
    return true;
}

export function HabitsCompletionRequestFromJSON(json: any): HabitsCompletionRequest {
    return HabitsCompletionRequestFromJSONTyped(json, false);
}

export function HabitsCompletionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HabitsCompletionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'completed': json['completed'] == null ? undefined : json['completed'],
    };
}

export function HabitsCompletionRequestToJSON(json: any): HabitsCompletionRequest {
    return HabitsCompletionRequestToJSONTyped(json, false);
}

export function HabitsCompletionRequestToJSONTyped(value?: HabitsCompletionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed': value['completed'],
    };
}

