/* tslint:disable */
/* eslint-disable */
/**
 * HabitMuse API
 * API для управления привычками и пользователями
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HabitsHabitDto } from './HabitsHabitDto';
import {
    HabitsHabitDtoFromJSON,
    HabitsHabitDtoFromJSONTyped,
    HabitsHabitDtoToJSON,
    HabitsHabitDtoToJSONTyped,
} from './HabitsHabitDto';

/**
 * 
 * @export
 * @interface HabitsHabitCompletionDto
 */
export interface HabitsHabitCompletionDto {
    /**
     * 
     * @type {boolean}
     * @memberof HabitsHabitCompletionDto
     */
    completed: boolean;
    /**
     * 
     * @type {string}
     * @memberof HabitsHabitCompletionDto
     */
    completedDay: string;
    /**
     * 
     * @type {HabitsHabitDto}
     * @memberof HabitsHabitCompletionDto
     */
    habit: HabitsHabitDto;
}

/**
 * Check if a given object implements the HabitsHabitCompletionDto interface.
 */
export function instanceOfHabitsHabitCompletionDto(value: object): value is HabitsHabitCompletionDto {
    if (!('completed' in value) || value['completed'] === undefined) return false;
    if (!('completedDay' in value) || value['completedDay'] === undefined) return false;
    if (!('habit' in value) || value['habit'] === undefined) return false;
    return true;
}

export function HabitsHabitCompletionDtoFromJSON(json: any): HabitsHabitCompletionDto {
    return HabitsHabitCompletionDtoFromJSONTyped(json, false);
}

export function HabitsHabitCompletionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HabitsHabitCompletionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'completed': json['completed'],
        'completedDay': json['completedDay'],
        'habit': HabitsHabitDtoFromJSON(json['habit']),
    };
}

export function HabitsHabitCompletionDtoToJSON(json: any): HabitsHabitCompletionDto {
    return HabitsHabitCompletionDtoToJSONTyped(json, false);
}

export function HabitsHabitCompletionDtoToJSONTyped(value?: HabitsHabitCompletionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed': value['completed'],
        'completedDay': value['completedDay'],
        'habit': HabitsHabitDtoToJSON(value['habit']),
    };
}

