/* tslint:disable */
/* eslint-disable */
/**
 * HabitMuse API
 * API для управления привычками и пользователями
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersUser
 */
export interface UsersUser {
    /**
     * 
     * @type {string}
     * @memberof UsersUser
     */
    createAt?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersUser
     */
    lastName?: string;
    /**
     * 
     * @type {number}
     * @memberof UsersUser
     */
    userID?: number;
    /**
     * 
     * @type {string}
     * @memberof UsersUser
     */
    userName?: string;
}

/**
 * Check if a given object implements the UsersUser interface.
 */
export function instanceOfUsersUser(value: object): value is UsersUser {
    return true;
}

export function UsersUserFromJSON(json: any): UsersUser {
    return UsersUserFromJSONTyped(json, false);
}

export function UsersUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersUser {
    if (json == null) {
        return json;
    }
    return {
        
        'createAt': json['createAt'] == null ? undefined : json['createAt'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'userID': json['userID'] == null ? undefined : json['userID'],
        'userName': json['userName'] == null ? undefined : json['userName'],
    };
}

export function UsersUserToJSON(json: any): UsersUser {
    return UsersUserToJSONTyped(json, false);
}

export function UsersUserToJSONTyped(value?: UsersUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createAt': value['createAt'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'userID': value['userID'],
        'userName': value['userName'],
    };
}

