definitions:
  users.User:
    properties:
      createAt:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      userID:
        type: integer
      userName:
        type: string
    type: object
  users.UserTGDTO:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      userId:
        type: integer
      userName:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для управления привычками и пользователями
  title: HabitMuse API
  version: "1.0"
paths:
  /api/user/registration:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя
      parameters:
      - description: Информация о пользователе
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.UserTGDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
      summary: Регистрация пользователя
      tags:
      - users
swagger: "2.0"
