definitions:
  body_metrics.BodyMetricDTO:
    properties:
      belly:
        type: number
      biceps_left:
        type: number
      biceps_right:
        type: number
      chest:
        type: number
      date:
        type: string
      hips:
        type: number
      thigh_low_left:
        type: number
      thigh_low_right:
        type: number
      thigh_max_left:
        type: number
      thigh_max_right:
        type: number
      waist:
        type: number
      weight:
        type: number
    required:
    - date
    type: object
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  habits.CompletionRequest:
    properties:
      completed:
        type: boolean
    type: object
  habits.CreateHabitDto:
    properties:
      color:
        type: string
      daysOfWeek:
        type: string
      desc:
        type: string
      firstDate:
        description: '"2025-06-28T00:00:00Z"'
        type: string
      icon:
        type: string
      name:
        type: string
      repeatType:
        type: string
    required:
    - color
    - firstDate
    - icon
    - name
    - repeatType
    type: object
  habits.HabitCompletionDto:
    properties:
      completed:
        type: boolean
      completedDay:
        format: "2006-01-02"
        type: string
      habit:
        $ref: '#/definitions/habits.HabitDto'
    required:
    - completed
    - completedDay
    - habit
    type: object
  habits.HabitDto:
    properties:
      color:
        type: string
      daysOfWeek:
        type: string
      desc:
        type: string
      firstDate:
        description: '"2025-06-28T00:00:00Z"'
        type: string
      icon:
        type: string
      id:
        type: string
      name:
        type: string
      repeatType:
        type: string
      versionId:
        type: integer
    required:
    - color
    - firstDate
    - icon
    - id
    - name
    - repeatType
    - versionId
    type: object
  habits.UpdateHabitDto:
    properties:
      color:
        type: string
      daysOfWeek:
        type: string
      desc:
        type: string
      firstDate:
        description: '"2025-06-28T00:00:00Z"'
        type: string
      icon:
        type: string
      name:
        type: string
      repeatType:
        type: string
    required:
    - color
    - firstDate
    - icon
    - name
    - repeatType
    type: object
  users.User:
    properties:
      createAt:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      userID:
        type: integer
      userName:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для управления привычками и пользователями
  title: HabitMuse API
  version: "1.0"
paths:
  /api/body-metric:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Готовый текстовый отчет
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получить отчет по метрикам тела
      tags:
      - BodyMetrics
  /api/body-metric/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные метрики
        in: body
        name: metric
        required: true
        schema:
          $ref: '#/definitions/body_metrics.BodyMetricDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/body_metrics.BodyMetricDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Создать метрику тела
      tags:
      - BodyMetrics
  /api/habit/:
    get:
      description: Returns all active habits for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/habits.HabitDto'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      tags:
      - habits
  /api/habit/{groupId}:
    get:
      description: Returns a single active habit by group ID
      parameters:
      - description: Habit group ID
        in: path
        name: groupId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/habits.HabitDto'
      tags:
      - habits
    post:
      consumes:
      - application/json
      parameters:
      - description: ID группы привычки
        in: path
        name: groupId
        required: true
        type: string
      - description: UpdateHabitDto
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/habits.UpdateHabitDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/habits.HabitDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Обновить привычку
      tags:
      - habits
  /api/habit/{groupId}/{versionId}:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID версии привычки
        in: path
        name: versionId
        required: true
        type: integer
      - description: ID привычки
        in: path
        name: groupId
        required: true
        type: integer
      - description: Обновлённые данные привычки
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/habits.UpdateHabitDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/habits.HabitDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Обновить привычку по версии
      tags:
      - habits
  /api/habit/{groupId}/disable:
    put:
      parameters:
      - description: ID привычки
        in: path
        name: groupId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Скрыть (отключить) привычку
      tags:
      - habits
  /api/habit/{versionId}/{date}:
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID версии привычки
        in: path
        name: versionId
        required: true
        type: integer
      - description: Дата (в формате 2006-01-02)
        in: path
        name: date
        required: true
        type: string
      - description: Completion status
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/habits.CompletionRequest'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Отметить выполнение привычки на дату
      tags:
      - habits
  /api/habit/completion/{date}:
    get:
      description: Returns all completed or active habits for a user on a given date
      parameters:
      - description: Date in format YYYY-MM-DD
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/habits.HabitCompletionDto'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      tags:
      - habits
  /api/habit/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: CreateHabitDto
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/habits.CreateHabitDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/habits.HabitDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Создать новую привычку
      tags:
      - habits
  /api/user/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
      summary: Получить Пользователя из контекста
      tags:
      - users
  /body-metric/all:
    get:
      description: Возвращает список всех записей метрик тела текущего авторизованного
        пользователя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/body_metrics.BodyMetricDTO'
            type: array
        "401":
          description: Пользователь не найден в контексте
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получить список всех метрик тела пользователя
      tags:
      - body-metric
swagger: "2.0"
