definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  habits.CompletionRequest:
    properties:
      completed:
        type: boolean
    type: object
  habits.HabitCompletionDto:
    properties:
      completed:
        type: boolean
      completedDay:
        format: "2006-01-02"
        type: string
      habit:
        $ref: '#/definitions/habits.HabitDto'
    type: object
  habits.HabitDto:
    properties:
      color:
        type: string
      daysOfWeek:
        type: string
      desc:
        type: string
      firstDate:
        description: '"2025-06-28T00:00:00Z"'
        type: string
      icon:
        type: string
      id:
        type: string
      name:
        type: string
      repeatType:
        type: string
      versionId:
        type: integer
    type: object
  users.User:
    properties:
      createAt:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      userID:
        type: integer
      userName:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для управления привычками и пользователями
  title: HabitMuse API
  version: "1.0"
paths:
  /api/habit/:
    get:
      description: Returns all active habits for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/habits.HabitDto'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      tags:
      - habits
  /api/habit/{groupId}:
    get:
      description: Returns a single active habit by group ID
      parameters:
      - description: Habit group ID
        in: path
        name: groupId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/habits.HabitDto'
      tags:
      - habits
  /api/habit/{versionId}/{date}:
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID версии привычки
        in: path
        name: versionId
        required: true
        type: integer
      - description: Дата (в формате 2006-01-02)
        in: path
        name: date
        required: true
        type: string
      - description: Completion status
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/habits.CompletionRequest'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Отметить выполнение привычки на дату
      tags:
      - habits
  /api/habit/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: HabitDto
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/habits.HabitDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/habits.HabitDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Создать новую привычку
      tags:
      - habits
  /api/habit/update/{groupId}:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID группы привычки
        in: path
        name: groupId
        required: true
        type: string
      - description: HabitDto
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/habits.HabitDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/habits.HabitDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Обновить привычку
      tags:
      - habits
  /api/user/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
      summary: Получить Пользователя из контекста
      tags:
      - users
  /habit/completion/{date}:
    get:
      description: Returns all completed or active habits for a user on a given date
      parameters:
      - description: Date in format YYYY-MM-DD
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/habits.HabitCompletionDto'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      tags:
      - habits
swagger: "2.0"
