name: main.yml
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Install dependencies
        run: go get .
      - name: Build be
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache-dependency-path: ./webapp/package-lock.json
          cache: npm
      - run: npm ci
        working-directory: ./webapp
      - run: npm run build
        working-directory: ./webapp
      - name: Upload build results
        uses: actions/upload-artifact@v4
        with:
          name: habit-bot
          path: |
            ./HabitMuse
            ./resources
            ./webapp/dist

  deploy:
    environment: production
    env:
      TARGET_DIR: HabitBot
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: habit-bot
      - name: Add executable
        run: chmod +x ./HabitMuse
      - name: Create .env
        env:
          SECRETS: ${{ toJson(secrets) }}
        run: |
          echo "$SECRETS" | jq -r 'to_entries[] | select( .key | test("^APP_") ) | ( .key | sub("^APP_"; "") ) + "=" + ( .value|@json )' >> .env
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/vps.key
          chmod 600 ~/.ssh/vps.key
          cat >>~/.ssh/config <<END
          Host vps
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/vps.key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USER: ${{ secrets.VPS_USERNAME }}
          SSH_KEY: ${{ secrets.VPS_KEY }}
      - name: Clear target upload folder
        run: |
          ssh vps << EOF
            rm -rf ~/$TARGET_DIR.new 
            mkdir ~/$TARGET_DIR.new
          EOF
      - name: Upload everything
        run: scp -r ./. vps:~/$TARGET_DIR.new/
      - name: Rotate deployment folders
        run: |
          ssh vps <<EOF
            rm -rf ~/$TARGET_DIR.old 
            mkdir -p ~/$TARGET_DIR/
            cp -r ~/$TARGET_DIR/. ~/$TARGET_DIR.old
            rm -rf ~/$TARGET_DIR/HabitMuse ~/$TARGET_DIR 
            cp -r ~/$TARGET_DIR.new/. ~/$TARGET_DIR
          EOF
