name: workflow.yml
on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Install dependencies
        run: go get .
      - name: Build be
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: npm
      - run: npm ci
        working-directory: ./webapp
      - run: npm run build
        working-directory: ./webapp
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: habit-bot
          path: |
            ./HabitMuse
            ./webapp/dist